# Generated by Django 5.2.18 on 2026-10-09 07:35

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=12)),
                ('duration_semesters', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_program_code')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('cnic', models.CharField(help_text='CNIC or B-Form: 12345-1234567-1', max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/')),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_cnic', models.CharField(max_length=15)),
                ('guardian_occupation', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('registration_no', models.CharField(max_length=20)),
                ('semester', models.PositiveSmallIntegerField()),
                ('session', models.CharField(help_text='e.g. 2024-2028', max_length=20)),
                ('previous_qualification', models.CharField(max_length=100)),
                ('previous_institute', models.CharField(max_length=150)),
                ('marks_or_cgpa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('branch_selected_at', models.DateTimeField(blank=True, null=True)),
                ('datesheet_saved_at', models.DateTimeField(blank=True, null=True)),
                ('branch_unlocked', models.BooleanField(default=False)),
                ('datesheet_unlocked', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='branches.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='students.student')),
            ],
            options={
                'ordering': ['course__code'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'semester'], name='student_program_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'datesheet_saved_at'], name='student_branch_saved_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(condition=models.Q(('datesheet_saved_at__isnull', True)), fields=['created_at'], name='student_not_saved_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='student_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='student',
            index=django.contrib.postgres.indexes.GinIndex(fields=['registration_no'], name='student_regno_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('cnic',), name='unique_student_cnic'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('registration_no',), name='unique_student_registration_no'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('semester__gte', 1), ('semester__lte', 12)), name='student_semester_1_12'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('marks_or_cgpa__gte', 0)), name='student_marks_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_assignment'),
        ),
    ]
