# Generated by Django 5.2.18 on 2026-10-09 07:35

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('branches', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity_per_branch', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='courses.course')),
            ],
            options={
                'ordering': ['start_at', 'course__code'],
            },
        ),
        migrations.CreateModel(
            name='DatesheetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('during', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='branches.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='students.student')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='scheduling.examslot')),
            ],
            options={
                'ordering': ['during'],
            },
        ),
        migrations.CreateModel(
            name='SlotSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('booked', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='branches.branch')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='scheduling.examslot')),
            ],
        ),
        migrations.AddIndex(
            model_name='examslot',
            index=models.Index(fields=['course', 'start_at'], name='slot_course_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.UniqueConstraint(fields=('course', 'start_at'), name='unique_slot_per_course_start'),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_per_branch__isnull', True), ('capacity_per_branch__gt', 0), _connector='OR'), name='slot_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='datesheetselection',
            index=models.Index(fields=['slot', 'branch'], name='selection_slot_branch_idx'),
        ),
        migrations.AddConstraint(
            model_name='datesheetselection',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='one_slot_per_course'),
        ),
        migrations.AddConstraint(
            model_name='datesheetselection',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('student', '='), ('during', '&&')], name='no_overlapping_exams'),
        ),
        migrations.AddConstraint(
            model_name='slotseat',
            constraint=models.UniqueConstraint(fields=('slot', 'branch'), name='unique_seat_slot_branch'),
        ),
        migrations.AddConstraint(
            model_name='slotseat',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('booked__lte', models.F('capacity')), _connector='OR'), name='seat_booked_within_capacity'),
        ),
    ]
